# Generated by Django 4.0.4 on 2022-06-21 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='', verbose_name='User')),
                ('post', models.TextField(blank=True, default='', verbose_name='Post')),
                ('isliked', models.BooleanField(default=False)),
                ('liked', models.IntegerField(default=0, verbose_name='Liked')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Publication Datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(default=True)),
                ('joke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.joke')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
