# Generated by Django 4.0.5 on 2022-06-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_joke_delete_user_activity_joke_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='joke',
            old_name='user',
            new_name='username',
        ),
    ]
