# Generated by Django 4.0.5 on 2022-06-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_activity_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='joke',
            old_name='username',
            new_name='user',
        ),
    ]
